controllers:
    resource: '../src/Controller/'
    type:     annotation

logout:
    path: /logout

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /cats
        permanent: true